const test=require('node:test'),assert=require('node:assert/strict');
const {compareInventory}=require('./verify-tampermonkey.cjs');
const expected={scripts:[{uuid:'a',name:'Active',version:'1',enabled:true,requiredApproval:true,sourceHash:'code',storageHash:'gm'},{uuid:'b',name:'Disabled',version:'1',enabled:false,requiredApproval:false,sourceHash:'off-code',storageHash:'off-gm'}]};
function current(){return {scripts:expected.scripts.map(s=>({...s,evilness:0})),registered:2}}
test('registered dispatcher bundles do not imply scripts are approved',()=>{const actual=current();actual.scripts[0].evilness=12;assert.throws(()=>compareInventory(expected,actual),/approval/)});
test('disabled script remains disabled and preserved',()=>{const actual=current();actual.scripts[1].evilness=12;assert.equal(compareInventory(expected,actual).enabled,1);actual.scripts[1].enabled=true;assert.throws(()=>compareInventory(expected,actual),/enabled/)});
test('source and GM data mismatches fail without exposing content',()=>{for(const key of ['sourceHash','storageHash']){const actual=current();actual.scripts[0][key]='changed';assert.throws(()=>compareInventory(expected,actual),new RegExp(key))}});
test('metadata approvals can be pending before supported UI repair',()=>{const actual=current();actual.scripts[0].evilness=12;assert.equal(compareInventory(expected,actual,{requireApproval:false}).blocked,1)});
test('automatic-update flags are preserved when the manifest specifies them',()=>{const manifest=structuredClone(expected);manifest.scripts[0].checkForUpdates=true;manifest.scripts[0].locallyModified=false;const actual=current();actual.scripts[0].checkForUpdates=true;actual.scripts[0].locallyModified=false;assert.equal(compareInventory(manifest,actual).enabled,1);actual.scripts[0].locallyModified=true;assert.throws(()=>compareInventory(manifest,actual),/locallyModified/);actual.scripts[0].locallyModified=false;actual.scripts[0].checkForUpdates=false;assert.throws(()=>compareInventory(manifest,actual),/checkForUpdates/)});
